### ISSUE TITLE
macOS 12.1 is required 

### ISSUE THREAD

**Issue by davidem** [neilsardesai/Manila#2]
Perhaps it is nice to mention that macOS 12.1 or later is required 😎

<img width="624" alt="image" src="https://user-images.githubusercontent.com/706591/159180003-068fd80c-d164-4ca4-9cbc-24be1988e5af.png">

**Comment by neilsardesai** [comment]
Hi David,
Thanks for the feedback. I’ve updated the readme to include this information.
Cheers,
Neil

**Comment by daumiller** [comment]
If you replace all the localized string constructors with plain strings, (and, obviously, change the target version), it compiles and runs just fine on 11.6.4 (don't know about earlier versions). I've been running a locally modified copy on Big Sur for a few days now, just fine.
