### ISSUE TITLE
Feature request: Homebrew cask

### ISSUE THREAD

**Issue by otherguy** [neilsardesai/Manila#5]
Thanks for making Manila! :) 

Would be great if we could install it via [Homebrew](https://brew.sh)

**Comment by bchatard** [comment]
@otherguy https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/manila.rb

**Comment by otherguy** [comment]
Nice! :) 

<img width="1016" alt="CleanShot 2022-05-17 at 11 18 48@2x" src="https://user-images.githubusercontent.com/6072721/168776868-eb6e5e67-819b-468b-9b06-82c91188be0b.png">
