### ISSUE TITLE
Feature Request: Reside in Menubar rather than Dock

### ISSUE THREAD

**Issue by mctinker** [neilsardesai/Manila#7]
Ideally, this is a great candidate for the menubar rather than taking up another slot on the desktop dock.

**Comment by neilsardesai** [comment]
Hi mctinker,

Manilla is a **Finder Extension** and will continue to work after you close the main app's window. It doesn't need to be open and taking up space in your dock. 

<img width="646" alt="Screen Shot 2022-09-23 at 9 49 07 AM" src="https://user-images.githubusercontent.com/4098825/191975686-1a5bb0fd-5307-4fa8-aeb8-17e8741b931e.png">
